### ISSUE TITLE
Replication tests

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#139]
- [x] `gatys_ecker_bethge_2016` (#117)
- [x] `gatys_et_al_2017` (#140)
- [x] `johnson_alahi_li_2016` (#137)
- [x] `li_wand_2016` (#141)
- [x] `ulyanov_et_al_2016` (#142)
