### ISSUE TITLE
Port reference implementation and replication scripts

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#9]
We need to port the reference implementations from [`pystiche.papers`](https://github.com/pmeier/pystiche/tree/master/pystiche/papers) and the replication scripts for [`pystiche_replication`](/pmeier/pystiche_replication).

- [x] `gatys_ecker_bethge_2015` (#6)
- [x] `li_wand_2016` (#14)
- [x] `johnson_alahi_li_2016` (#10)
- [x] `ulyanov_et_al_2016` (#17)
- [x] `gatys_et_at_2017` (#18)

Additionally some other features should be ported

- [x] `pystiche.misc.cuda` (#5, #8)
- [x] `pystiche.papers.common_utils` (#5, #8)
- [x] `pystiche.data.NPRgeneral` (#1)
